### ISSUE TITLE
[BUG] typo in create_session_builder.py

### ISSUE THREAD

**Issue by will-riley** [iluvcapra/py-ptsl#25]
master/current

create_session_builder.py, line 61 - function name "interlaved".

**Comment by iluvcapra** [comment]
Will try to slip this into PR#24

**Comment by iluvcapra** [comment]
Fixed in [e3db0a5](https://github.com/iluvcapra/py-ptsl/commit/e3db0a510162c55c3e43b6fd39cdab460102b2f5)
