### ISSUE TITLE
[BUG] error when trying to run "get_memory_locations"

### ISSUE THREAD

**Issue by evanmang** [iluvcapra/py-ptsl#33]
**Describe the bug**
Thanks for the work on this!! Having some issues with a few commands, particularly "get_memory_locations". 

**To Reproduce**
Please enter code here that demonstrates the bug:
```python

import sys

from ptsl import open_engine
from ptsl import PTSL_pb2 as pt

with open_engine(company_name="py-ptsl",
                 application_name=sys.argv[0]) as engine:

    markers = engine.get_memory_locations()
    print(markers)

```

**Expected behavior**
Output of memory location data from open session.

**Error Message**
`Traceback (most recent call last):
  File "/Users/heardstudio/Desktop/PTSL/py-ptsl-master/examples/memloctext.py", line 11, in <module>
    markers = engine.get_memory_locations()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ptsl/engine.py", line 446, in get_memory_locations
    self.client.run(op)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ptsl/client.py", line 161, in run
    raise CommandError(command_errors.errors)
ptsl.errors.CommandError: ErrType 100: PT_UnknownError (VENUE is not connected)`

**Platform:**
- Operating System: macOS 12.7.4
- Pro Tools Version: 2024.3.1 / 2023.12

**Additional context**
Tested with 2023.12 and 2024.3.1, verified many other commands are working, the included examples and a bunch of other random commands.

**Comment by StephenMachete** [comment]
Hi evan, try to specify the address to connect like:
with open_engine(company_name="py-ptsl", application_name=sys.argv[0], address="localhost:31416") as engine:

Usually the address should be set as default. But i think i had the same error after building on mac. Took me ages to find :D On Win i never had this.
Can you report if this fixed it?
If yes.. @iluvcapra any clue why this happening?

**Comment by evanmang** [comment]
Thanks Stephen,

I get the same error when i specify the address and run the 'get_memory_locations' command. Other commands 'track_list' for example, work fine with/without the address.

**Comment by StephenMachete** [comment]
I think i found the issue. GetMemoryLocation now needs a pagination_request. The fix looks like this in the engine.py:
    def get_memory_locations(self) -> List[pt.MemoryLocation]:
        """
        Get a list of all memory locations in currently-open session.
        """
        op = ops.GetMemoryLocations(pagination_request=pt.PaginationRequest(limit=1000, offset=0))
        self.client.run(op)
        return op.response.memory_locations

**Comment by evanmang** [comment]
@StephenMachete that works! Thanks!
