### ISSUE TITLE
Can't access to timeline / Can you help me out?

### ISSUE THREAD

**Issue by rhinofug** [iluvcapra/py-ptsl#41]
**Describe the bug**
CommandError: ErrType 100: PT_UnknownError (VENUE is not connected)
Press any key to continue . . .

**To Reproduce**
from ptsl import open_engine, errors

# Provide your company name and application name
company_name = "fugCompany"
application_name = "fug1"

try:
    # Open the engine with the specified company and application names
    with open_engine(company_name=company_name, application_name=application_name) as engine:
        
        # Get a list of all memory locations
        memory_locations = engine.get_memory_locations()
        
       
        
except errors.CommandError as e:
    print(f"CommandError: {e}")
except Exception as e:
    print(f"An error occurred: {e}")

```python

assert True

```

**Platform:**
 Operating System: Windows 10 Pro 64-bit
 Processor: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 CPUs), ~2.2GHz
 Memory: 8192MB RAM
 ProTools Intro: V2024.3.1
 Pyhton 3.12
 VS Community 2022
 Py-Ptsl Ptsl V1

**Additional context**
Same error with this code too:

from ptsl import open_engine, errors

# Provide your company name and application name
company_name = "fugCompany"
application_name = "fug1"

try:
    # Open the engine with the specified company and application names
    with open_engine(company_name=company_name, application_name=application_name) as engine:
        # Retrieve the current timeline selection using the engine object
        in_time, out_time = engine.get_timeline_selection()
        
        # Now you can work with the timeline selection times
        print("Timeline selection In time:", in_time)
        print("Timeline selection Out time:", out_time)
except errors.CommandError as e:
    print(f"CommandError: {e}")
except Exception as e:
    print(f"An error occurred: {e}")

**Comment by iluvcapra** [comment]
Can you confirm what version of py-ptsl you're using? 

Also I think you're the first person I'm aware of trying to do this with Pro Tools Into, it might not work.

**Comment by rhinofug** [comment]
Name: py-ptsl
Version: 301.0.0

I don't normally use ProTools for my main DAW thats why. But Avid Dev's Team said it should work with Pro Tools Intro (cRPG module)
I don't have problems with other scripts such as consolidate or export.
But I can't reach the data of the timeline.

**Comment by rhinofug** [comment]
from ptsl import open_engine, errors
from ptsl.engine import Engine

# Provide your company name and application name
company_name = "fugCompany"
application_name = "fug1"

try:
    # Open the engine with the specified company and application names
    with open_engine(company_name=company_name, application_name=application_name) as engine:
        
        # Get a list of all memory locations
     Engine.get_memory_locations()
        
       
        
except errors.CommandError as e:
    print(f"CommandError: {e}")
except Exception as e:
    print(f"An error occurred: {e}")

**Comment by StephenMachete** [comment]
Hi, it's the PaginationRequest again.
@rhinofug you installed the lib through pip?
Just download the engine.py here, and replace the one in your library. Or uninstall py-ptsl and reinstall from this repository.
@iluvcapra pip isn't updated with the last merge.

Peace
Steve

**Comment by rhinofug** [comment]
Yeah I've installed it trough pip. Ok doing it now. Thanks.

Peace,
Utku

**Comment by rhinofug** [comment]
I've reinstalled with 

$ python3 -m pip install .[doc]

after a restart it works like a charm. Thank you so much! @StephenMachete
